// <auto-generated />
using DataUploader.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataUploader.Migrations
{
    [DbContext(typeof(DalexDbContext))]
    partial class DalexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataUploader.Models.Attendant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BranchName");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Attendants");
                });

            modelBuilder.Entity("DataUploader.Models.Branch", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Code");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("DataUploader.Models.Paddie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BranchCode");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Paddies");
                });

            modelBuilder.Entity("DataUploader.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BranchCode");

                    b.Property<string>("Number");

                    b.Property<int>("PaddieId");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode");

                    b.HasIndex("PaddieId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("DataUploader.Models.Paddie", b =>
                {
                    b.HasOne("DataUploader.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchCode");
                });

            modelBuilder.Entity("DataUploader.Models.Ticket", b =>
                {
                    b.HasOne("DataUploader.Models.Branch", "Branch")
                        .WithMany("Tickets")
                        .HasForeignKey("BranchCode");

                    b.HasOne("DataUploader.Models.Paddie", "Paddie")
                        .WithMany("Tickets")
                        .HasForeignKey("PaddieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
